#!/bin/bash

echo ""
echo "

The getaddressesbyaccount RPC returns a list of every address assigned to a particular account.

Parameter #1—the account name
Result—a list of addresses
"
echo ""
echo "Dependencies:"
echo "getaccountaddress_WVA RPC"
echo ""

echo "Scenario: Verify the list the all addresses associated with RPCtesting account"
echo "Result:   Valid Addresses list"
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaddressesbyaccount\",\"account\":\"testRPCBTC\"}"

echo ""
