#!/bin/bash

echo ""
echo "

The getaccountaddress RPC returns the current Bitcoin address for receiving payments to this account. If the account doesn’t exist, it creates both the account and a new address for receiving payment. Once a payment has been received to an address, future calls to this RPC for the same account will return a different address.

Parameter #1 an account name
Result     bitcoin address
"
echo ""
echo ""
echo "Dependencies:"
echo "Walletpassphrase RPC, incase wallet is locked"
echo ""
echo "Result: Bitcoin address should be generated and the name of account should be set to RPCtesting"
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccountaddress\",\"account\":\"RPCtesting\"}"

echo ""
