#!/bin/bash

echo ""
echo " The getreceivedbyaddress RPC returns the total amount received by the specified address in transactions with the specified number of confirmations. It does not count coinbase transactions.

Parameter #1—the address
Parameter #2—the minimum number of confirmations
Result—the number of bitcoins receiv"

echo ""
echo "Dependencies:"
echo "Wallpassphrase, incase wallet is locked"
echo "getaccountaddres, incase account and address don't exist already"
echo "sendtoaddress, if you want to send some coins to that address"
echo ""

echo  "Senario: Verify that correct amount is returned for mentioned address"
echo  "Result: Correct amount for provided address should be returned"
echo ""

#RCEZoVBCHaZDyP4ocyhS3F2TN2EMVsPzcT

#RL1tyXPK5NzT1d4upgcHnujgG5v3xjLaYC
curl --url "http://127.0.0.1:7778" --data "{\"method\":\"getreceivedbyaddress\",\"params\":[\"RCEZoVBCHaZDyP4ocyhS3F2TN2EMVsPzcT\"]}"
echo ""
