#! /bin/bash

echo "RPC: getrawtransaction"
echo "The getrawtransaction RPC gets a hex-encoded serialized transaction or a JSON object describing the transaction"
echo "Parameter: the TXID of the transaction to get"
echo ""
echo "Result (if transaction not found)—null"


curl --url "http://127.0.0.1:7778"  --data "{\"method\":\"getrawtransaction\",\"params\":[\"fe9ba49c411ee7b3ae16f8de6f2e32b4ea469a8ff64766be113817646100bb56\"]}"

