#! /bin/bash

echo "RPC: sendmany"
echo "The sendmany RPC creates and broadcasts a transaction which sends outputs to multiple addresses"
echo "Parameters:"
echo "Parameter #1—from account- Address of account from where need to transfer BitCoin, empty in case of default"
echo "Parameter #2—the addresses and amounts to pay"
echo "Parameter #3—minimum confirmations"

echo "Result:TXID of the sent transaction"
echo ""


curl --url "http://127.0.0.1:7778" --data "{\"method\":\"sendmany\", \"params\":[\"\", {\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XZ\":0.01, \"1353tsE8YMTA4EuV7dgUXGjNFf9KpVvKHz\":0.02}, 2]}"
