#!/bin/bash

echo ""
echo "The setaccount RPC put the specified address in the given account"
echo ""
echo "Dependencies:"
echo "Getnewaddress RPC, if you don't have an address already"
echo "Getaccountaddress RPC, if account doesn't exist already"
echo ""
echo "Scenario: Verify that user is able to linked address with specified account"
echo "Result:   Address should be linked to mentioned account"
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"method\":\"setaccount\",\"params\":[\"RL1tyXPK5NzT1d4upgcHnujgG5v3xjLaYC\", \"RPCtesting\"]}"
