#! /bin/bash

echo "RPC: validateaddress"
echo "The validateaddress RPC accepts a block, verifies it is a valid addition to the block chain, and broadcasts it to the network."
echo ""
echo "Result: information about the address "
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"validateaddress\",\"address\":\"RK4Frtw5N5Zm6MrUjgmh8ZG1JGEtRJgXVo\"}"
